mon_agence_immo/src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use App\Repository\PropertyRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PropertyRepository::class)]
class Property
{
    //le chauffage
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $surface = null;

    #[ORM\Column]
    private ?int $rooms = null;

    #[ORM\Column]
    private ?int $bedrooms = null;

    #[ORM\Column]
    private ?int $floor = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column]
    private ?int $postal_code = null;

    #[ORM\Column]
    private ?int $heat = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column]
    private ?bool $sold = null;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', '');
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?int
    {
        return $this->postal_code;
    }

    public function setPostalCode(int $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function isSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }
}

mon_agence_immo/templates/pages/home.html.twig
{% extends "base.html.twig"%}

{% block body %}

{% block title 'Ma super agence immo' %}
<div class="jumbontron text-center mx-5">
    <h1>Ma super Agence immo</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi hic eveniet praesentium suscipit eum qui? Illum
        voluptate, laudantium adipisci veritatis nostrum eius illo qui voluptatum eveniet nisi ullam, voluptatibus nam?
    </p>
</div>

<div class="container">
    <div class="row-flex">
        <h2>Les derniers biens</h2>
        {% for property in properties %}
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">{{property.title}}</a>
                    </h5>
                    <p class="card-text">{{property.city}} ({{property.postalCode}})</p>
                    <div class="text-primary">{{property.formattedPrice}} €</div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mon_agence_immo/templates/pages/index.html.twig
{% extends "base.html.twig"%}

{% block body %}

{% block title 'Ma super agence immo' %}
<div class="jumbontron text-center mx-5">
    <h1>Ma super Agence immo</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi hic eveniet praesentium suscipit eum qui? Illum
        voluptate, laudantium adipisci veritatis nostrum eius illo qui voluptatum eveniet nisi ullam, voluptatibus nam?
    </p>
</div>

<div class="container">
    <div class="row-flex">
        <h2>Les derniers biens</h2>
        {% for property in properties %}
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">{{property.title}}</a>
                    </h5>
                    <p class="card-text">{{property.city}} ({{property.postalCode}})</p>
                    <div class="text-primary">{{property.formattedPrice}} €</div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}